"""Create all tables

Revision ID: 81dc49a9feb9
Revises: 
Create Date: 2026-06-04 17:31:45.618577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dc49a9feb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydroponic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('moisture', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('humidity', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('ph', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('ec', sa.DOUBLE_PRECISION(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hydroponic'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hydroponic')
    # ### end Alembic commands ###
